//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Orders = new HashSet<Order>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn quyền")]
        public int RoleId { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập họ")]
        [MinLength(2, ErrorMessage = "Họ tên ít nhất phải có 2 ký tự")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên")]

        public string LastName { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Bạn chưa nhập đúng định dạng Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập mật khẩu")]
        [MinLength(6, ErrorMessage = "Mật khẩu ít nhất phải có 6 ký tự")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập xác nhận mật khẩu")]
        [MinLength(6, ErrorMessage = "Xác nhận mật khẩu ít nhất phải có 6 ký tự")]
        [Compare("Password", ErrorMessage = "Mật khẩu phải trùng với xác nhận mật khẩu")]
        public string ConfirmPassword { get; set; }
        public string ResetPasswordCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string UserImage { get; set; }
        public string Phone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
